language: python
python:
  - "3.9"

services:
  - docker

before_script:
  - pip install docker-compose

script:
  - docker-compose run app sh -c "sudo python manage.py makemigrations"
  - docker-compose run app sh -c "sudo python manage.py migrate"
  - docker-compose run app sh -c "sudo python manage.py test && flake8"