language: python
python:
  - "3.9"

services:
  - docker

before_script:
  - pip install docker-compose
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - docker-compose run app sh -c "python manage.py makemigrations"
  - docker-compose run app sh -c "python manage.py migrate"
  - docker-compose run app sh -c "python manage.py test && flake8"